name: ci

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Unit tests
        run: npm test
      - name: E2E tests
        run: npm run test:e2e:ci
      - name: Upload screenshots when spect fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./cypress/screenshots
      - name: Upload videos when spect fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: ./cypress/videos
